price counting, ingredients adding
polinakoma/react-burger pull request #5
Opened 2022-10-24 03:41 UTC by polinakoma

2022-10-24 05:44 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Исправить ошибки в консоли: https://yadi.sk/d/AIEEhww1uuTaOw.

- У вас не отображаются булки: https://yadi.sk/d/vgRS_RW2-YuDzw.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  }
**Можно лучше:** если нам не нужен `default case`, то лучше указать его таким образом: https://eslint.org/docs/rules/default-case.

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/App/App.jsx
>    const link = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/App/App.jsx
>    const getServerData = () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +              <BurgerConstuctor ingredients={ingredients} />
**Надо исправить:** Мы не используем больше эти пропсы, поэтому их следует удалить.

2022-10-24 05:44 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +    });
**Надо исправить:** цену лучше рассчитывать через useMemo. не стоит для этого использовать useEffect.

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +        })
**Можно лучше**

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
>                                  if(ingredient.type !== 'bun') {
**Можно лучше:** Лучше сделать фильтрацию до рендера `jsx`, используя useMemo.

2022-10-24 05:44 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +            {modalData && modal &&
**Можно лучше:** тут можно не использовать дополнительную проверку через `modal`. Можно просто оставить `modalData` и ставить ей `null`, при закрытии модального окна.

2022-10-26 02:07 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +    const [modal, setModal] = React.useState(null);
**Можно лучше:** Лучше удалить неиспользуемый useState.

2022-10-26 02:08 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. Все замечания с прошлого ревью были исправлены.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении!**

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-10-26 02:08 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +    const [modal, setModal] = React.useState(null);
**Можно лучше:** Лучше удалить неиспользуемый useState.

2022-11-16 13:29 UTC, merged