Month 9/step 2
polinakoma/react-burger pull request #8
Opened 2022-12-21 15:43 UTC by polinakoma

2022-12-27 12:52 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлении ленты заказов и сокетов в ваш проект, вёрстка корректная, код лаконичный и аккуратно разбит на нужные компоненты, присутствуют полезные комментарии, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- На экране профиля кнопки "Сохранить" и "Отмена" следует скрыть до момента изменения пользователем значений или при нажатии на кнопку "Отмена" (https://disk.yandex.ru/i/HUZrdYpoIx124w);
- Сокет-соединение следует закрывать и очищать очередь заказов, когда пользователь покидает экраны «Лента заказов» или «История заказов»; (https://disk.yandex.ru/i/E6KYHUhx5oHrfQ)
- При открытии модальных окон с информацией о заказе открывается дополнительное подключение (https://disk.yandex.ru/i/4JwaCZ3wi2PAMw - прямой переход по ссылке на заказ);
- В ходе выполнения одного и более заказов лента заказов "дергается", т.к. происходит ререндер всех компонентов карточки ленты из-за ключа в функции `map` (подробнее в OrderLines);
- Статус выполненного заказа некорректно отображается как "Создан" (см. https://disk.yandex.ru/i/jMI3BxyQL3sIBA);
- Иконка активной ссылки в хедере не изменяет свой цвет на белый (см. https://disk.yandex.ru/i/E3XKigee88CNmA);
- В конструкторе текст ингредиентов отображается с нижним подчеркиванием (автоматический стиль ссылки), согласно дизайну следует скорректировать;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-12-27 12:52 UTC, randomroot commented on src/utils/constans.js
> +export const pendingImage = 'https://stellarburgers.nomoreparties.site/static/media/loading.89540200.svg';
🔴 **Нужно исправить:**

Наименования всех **констант**, расположенных вне компонентов или функций, следует привести к стилю `UPPER_CASE`. Исключения составляют только переменные значение которых описывают `PropTypes`.

2022-12-27 12:52 UTC, randomroot commented on src/use-socket.ts
> +export const CONNECTING: 'CONNECTING' = 'CONNECTING';
🟢 **Отлично:**

Хорошо, что вынесли магические числа в отдельные значение 👍

2022-12-27 12:52 UTC, randomroot commented on src/components/ProfileOrders/ProfileOrders.js
> +            payload: `wss://norma.nomoreparties.space/orders?token=${accessToken?.replace('Bearer ', '')}`
🔴 **Нужно исправить:**

Общий путь до WS: `wss://norma.nomoreparties.space/` следует вынести в отдельную константу, аналогично `BURGER_API`

2022-12-27 12:52 UTC, randomroot commented on src/components/ProfileMenu/ProfileMenu.js
> +            <p className={`${styles.info} mt-20`}>В этом разделе вы можете изменить свои персональные данные</p>
🔴 **Нужно исправить:**

Согласно дизайну для экрана "Истории заказов" указан иной текст, следует обеспечить его переключение

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderItem/OrderItem.js
> +export default OrderItem;
🔴 **Нужно исправить:**

Для данного компонента следует указать `PropTypes`

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderItem/OrderItem.js
> +          allIngredients.find((allIngredient) => allIngredient._id === ingredient)
🟡 **Можно улучшить:**

Можно переиспользовать функцию `getSomeIngredient`

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderItem/OrderItem.js
> +            <div className={`${styles.orderItem} pt-6 pl-6 pr-6 pb-6 mb-4`}>
🟡 **Можно улучшить:**

Классы паддингов можно упростить до `p-6`, т.к. они одинаковые со всех сторон

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderItem/OrderItem.js
> +                    <p className={styles.orderNumber}>&#35;{number}</p>
🟡 **Можно улучшить:**

Лучше стараться не использовать коды символов, т.к. они не совсем очевидны, имеет смысл сформировать строку с помощью шаблонной строки ```{`...`}```

2022-12-27 12:52 UTC, randomroot commented on src/utils/constans.js
> +export const creationTime = (string) => {
🟡 **Можно улучшить:**

Название функций следует привести к виду "действие", например `getCreationDate`

2022-12-27 12:52 UTC, randomroot commented on src/utils/constans.js
> +export const orderStatus = (status) => {
🟡 **Можно улучшить:**

Название функций следует привести к виду "действие", например `getOrderStatus`

2022-12-27 12:52 UTC, randomroot commented on src/components/ProfileForm/ProfileForm.js
> +    const accessToken = getCookie('accessToken');
🟡 **Можно улучшить:**

Т.к. токен требуется только в рамках функции отправки формы, то имеет смысл перенести его именно туда, чтобы не обращаться за кукисом при каждом рендере

2022-12-27 12:52 UTC, randomroot commented on src/components/ProfileForm/ProfileForm.js
> +    const saveNewData = useCallback((e) => {
🟡 **Можно улучшить:**

Использование `useCallback` в данном случае излишне, т.к. в его зависимостях указаны по факту все переменные, от которых зависит перерендер всего компонента и функция будет всё равно пересоздаваться на каждом рендере, плюс накладывая дополнительные затраты на проверку массива. 

Интересная статья на эту тему: https://www.developerway.com/posts/how-to-use-memo-use-callback

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderLine/OrderLine.js
> +                                    if(order.status !== 'done') {
🔴 **Нужно исправить:**

Обратите внимание, что запросы могут придти в статусе "отменен" и тогда они попадут в эти столбики

2022-12-27 12:52 UTC, randomroot commented on src/components/OrderLine/OrderLine.js
> +                            <li key={index}>
🔴 **Нужно исправить:**

В качестве ключа не следует использовать индекс, за исключением случаев, когда вы точно уверены, что рендер произойдет один раз. В данном случае следует использовать идентификатор заказа для значения ключа, чтобы избежать лишних ре-рендеров

2022-12-27 20:17 UTC, polinakoma commented on src/components/ProfileForm/ProfileForm.js
> +    const saveNewData = useCallback((e) => {
Спасибо за статью

2022-12-28 13:46 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, **отлично**, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- В хедере могут отображаться активными две ссылки одновременно (см. https://disk.yandex.ru/i/h32G-kUtl6biAA);
- Сокет-соединение следует закрывать и очищать очередь заказов, когда пользователь покидает экраны «Лента заказов» или «История заказов»; (https://disk.yandex.ru/i/E6KYHUhx5oHrfQ);
- Следует прописать PropTypes у компонентов, которым были добавлены новые пропсы;

**Хорошего вам дня и настроения!** 🐈

2022-12-28 13:46 UTC, randomroot commented on src/utils/constans.js
> +export const CHECK_RESPONSE = (res) => {
🟡 **Можно улучшить:**

Функции необязательно переименовывать по правилу, описанному в предыдущем ревью, оно относится именно к константам-**значениям**, как выше например `WEB_SOCKET_URL`

2022-12-28 13:46 UTC, randomroot commented on src/components/OrderContentModal/OrderContentModal.js
> +export const OrderContentModal = ({isModal}) => {
🔴 **Нужно исправить:**

Следует прописать `PropTypes` для данного компонента

2022-12-28 13:46 UTC, randomroot commented on src/components/OrderItem/OrderItem.js
> +    order: PropTypes.object.isRequired
🟡 **Можно улучшить:**

Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

2022-12-28 17:01 UTC, polinakoma commented
Ваш комментарий: Сокет-соединение следует закрывать и очищать очередь заказов, когда пользователь покидает экраны «Лента заказов» или «История заказов»
Я не понимаю, что мне нужно сделать. При покидании «Лента заказов» или «История заказов» я диспатчу событие закрытия соединения в useEffect и очищаю очередь заказов allOrders: null

2022-12-28 18:05 UTC, polinakoma commented
В крайнем коммите исправлены все ошибки

2022-12-28 18:19 UTC, randomroot approved these changes
🟢 **Работа принята:**

Вы отлично поработали, внесли все необходимые правки, ваш код улучшен согласно рекомендациям, замечаний больше не имеется. Продолжайте в том же духе и вы достигнете невероятных высот ⭐

**Желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-30 20:39 UTC, merged