Month 10/step 1
polinakoma/react-burger pull request #9
Opened 2023-01-22 17:21 UTC by polinakoma

2023-01-25 18:05 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть 1 небольшое замечание, которое нужно исправить:**

- Не стоит явно указывать тип у литеральных констант, ведь такие константы, по умолчанию имеют тип равный её значению.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-01-25 18:05 UTC, ArslanMustafin commented on src/services/actions/ingredients.ts
> +export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
**Надо исправить:**

Здесь и в других местах.

Тут не стоит явно указывать тип, ведь константа по умолчанию при использовании typeof, будет выдавать значение.

2023-01-25 18:05 UTC, ArslanMustafin commented on src/services/actions/ingredients.ts
> +data: { ingredients: (string | undefined)[]; },
**Надо исправить:**

Лучше использовать такую запись:
```js
    accessToken?: string,
    data: { ingredients?: string[] },
```

2023-01-25 18:05 UTC, ArslanMustafin commented on src/components/OrderContentModal/OrderContentModal.tsx
> +          const orderedIngredient = allIngredients.find((item: IIngredient | undefined) =>
**Надо исправить:**

А вы точно уверены что там будет undefined?

2023-01-25 18:05 UTC, ArslanMustafin commented on src/components/OrderContentModal/OrderContentModal.tsx
> +    const ingredientCounter = (ingredient: IIngredient | undefined) => {
**Надо исправить:**

В этом и вдругих местах где у вас есть такая запись: `| undefined`, ещё раз убедитесь, что она действительно нужна))

2023-01-25 18:05 UTC, ArslanMustafin commented on src/components/OrderContentModal/OrderContentModal.tsx
>      const uniqueIngredient = Array.from(new Set(orderIngredients));
**Надо исправить:**

orderIngredients - лучше написать через reduce, чтобы в массив не попали undefined значения.

uniqueIngredient - при необходимости указать тип массива: `const uniqueIngredient = Array.from(new Set(orderIngredients)) as IIngredient[]`, но по идее, если правильно исправить первую функци, то это не понадобится.

2023-01-25 18:05 UTC, ArslanDev666 commented on src/pages/reset-password.tsx
> +    const settingNewPassword = useCallback((evt: any) =>  {
**Надр исправить:**

Вместо any можно использовать специальный тип `React.FormEvent<HTMLFormElement>`

2023-01-26 10:39 UTC, polinakoma commented on src/services/actions/ingredients.ts
> +data: { ingredients: (string | undefined)[]; },
при изменении на 
data: { ingredients?: string[] } 
возникает конфликт, что значение ingredients не может быть опциональным. Я сделала немного по-другому и надеюсь, что это приемлемо

2023-01-26 18:58 UTC, polinakoma commented on src/components/OrderContentModal/OrderContentModal.tsx
>      const uniqueIngredient = Array.from(new Set(orderIngredients));
Функцию переписала, однако как получить в orderIngredients только IIngredient[] без undefined я не поняла поэтому явно указала через as.

2023-01-27 03:22 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>      };
**Надо исправить:**

Вот так по идее проблем с типами быть не должно))

```js
    function openOrderModal() {
        if(!userInfo) {
            history.push('/login')
            return;
        } 

        const data = [
            addedIngredients.bun!._id,
            ...addedIngredients.ingredients.map((ingredient: IIngredient) => ingredient._id),
            addedIngredients.bun!._id
        ]  
        dispatch(getOrderNumber(data, setModalData, accessToken)) 
    };
```

также рекомендую отказаться от передачи `setModalData`. Вы ведь уже используете редакс, зачем допольнительно делать стейт для модального окна:?
И не забудьте сделать диспатч на обнуление в функции `closeModal`.

2023-01-27 03:22 UTC, ArslanDev666 commented on src/services/actions/ingredients.ts
> +(dispatch: AppDispatch) => {
**Надо исправить:**

Лучше написать вот так)) Старайтесь не использовать тип undefined и тип any, там где можно обойтись без них))

```js
export const getOrderNumber =
  (
    data: string[],
    accessToken: string
  ) =>
  (dispatch: AppDispatch) => {...}
```

2023-01-27 03:22 UTC, ArslanDev666 commented on src/components/OrderContentModal/OrderContentModal.tsx
>      const uniqueIngredient = Array.from(new Set(orderIngredients));
Гуд) функция переписана верно))
а `undefined` возникает из-за того, что `orderItem` может быть не найден)) 
тут 2 варианта как это можно обойти, либо поставить знак `!`, который говорит о том, что мы точно знаем, что у нас в переменной не будет `undefined`. Либо делать проверку.

```ts
// 1 вариант
const orderIngredients = orderItem!.ingredients.reduce(...)

// 2 вариант
if(!orderItem) {
 // допустим можно отправить пользователя на 404 страницу (страница не найдена) 
}

const orderIngredients = orderItem.ingredients.reduce(...)
```

2023-01-27 03:30 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! 🔥**

- Практически все замечания с прошлого ревью были исправлены;

### **Но есть пару небольших замечаний, которые нужно исправить:**

- Поправьте момент с `getOrderNumber`, показал как правильно это сделать в коде.

- Увеличьте `z-index` и уменьшите прозрачной у `modal-overlay`, а то пользователь не поймёт что это именно модальное окно, и что у него ничего не сломалось. <https://disk.yandex.com/i/4mDy46DUJIKJJQ> (на скрине я поменял прозрачность, чтобы показать что некоторые элементы имеют z-index превосходящий z-index modal-overlay)

2023-01-27 07:59 UTC, polinakoma commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>      };
Fetch запрос на отправку данных об айди ингредиентов должен содержать объект с ключом ingredients. Отправить данные массивом у меня не получилось - с сервера приходит отказ.

2023-01-27 17:06 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
>      };
Но ведь можно в самом запросе сделать объект и отправить его, а не передавать)) т.к. возможны такие варианты, когда вам надо будет в нескольких местах делать такой запрос, и вам каждый раз приходилось  бы создавать объект), а так вы просто передаёте массив, а объект уже делается в самом запросе.)

2023-01-27 17:09 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении! 🔥**

- Все замечания с прошлого ревью были исправлены;

2023-01-27 22:44 UTC, merged